# Generated by Django 3.0.5 on 2020-06-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_auto_20200621_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activity.User'),
        ),
    ]
